FROM ruby:2.7

ENV SERVICE_URL=https://open-vsx.org/vscode/gallery
ENV ITEM_URL=https://open-vsx.org/vscode/item

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g yarn

RUN curl -fsSL https://raw.githubusercontent.com/cdr/code-server/main/install.sh | sh

# RUN code-server --install-extension

CMD [ "code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080" ]